server:
  port: 9091
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21ds.aliyuncs.com:3306/any-platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: ss123
zookeeper:
  #address: 47.98.159.202:2181
  address: 127.0.0.1:2181
dubbo:
  group: any-center
  port: 20881
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/help-center-service.log
sms:
  expireTimeSecond: 60
token:
  expireTimeSecond: 3600
wechat:
  pc:
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
    userInfoUrl: https://api.weixin.qq.com/sns/userinfo
    pcAppID: wx66a3c02a7
    pcAppsecret: 241ad8d3138af34e6b5
  code:
    expireTimeSecond: 3600
  templateMessage:
    appID: wx6f29705e15
    appSecret: 3e50f0b50ed8f183bd66a6502
    accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
    templateMessageUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=ACCESS_TOKEN
    authDetailUrl: https://any-h5-test.shengsuvc.com/clue/library
pns:
  expireTimeSecond: 600
  areaCodes: 10
wxpay:
  appid: wx6f29768a15
  mchid: 1573621
  apikey: 1f5dc303b69e95fcad34ad34
  sandbox: false
  notifyUrl: https://any-platform-test.shengsuvc.com/api/wxpay/notify
alipay:
  appid: 2016101900724821
  rsaPrivateKey: MIIEvQIBADANBgkqhkASCBKcwggSjAgEAAoIBAQDeIdCxqIAk+8cvqmMmoVGoPG3+Z4P+TmgzNDxktOOvNIWV1opwZffvTGEq3Z70RZtGJC5Q0ojQma/jGWPzEP2qsjZOteJTVMWiCjSrbWAUwh23tsiNLNYiG+aGKfDf74MOI63cYuGeIz7gU+jd+1jxuHGgEzHr1PpTP4/AOAtFyvR8BjTuBL5j3AYWohaANynWjHZUw+phA7dmK7/7atHlMTcLFOQzt+mhutbaccVMx+IWAjC+u3QGKHIDccLoaMMkml/gwTWV8W2jqB+kGh12lqE1R/SBrU/qYV1kSwy/goIfQ0q7Pj5z1qU9Jg1vcvJYDTxI3VhbX06QRhx6ea0PAgMBAAECggEABhq1ynwP8XQ92BB9ow0h2la2yxv7I5zx/h48XqQd8a2m0iRQL6CNvLTDotLuUFYtWzMZVr1CZ0Eh9UK4XXClF/DHz0fuTU3yFG7lXaSm1Es1V9wdDMwjolJT9nHmnbDOUDAo0fqhqp/bVXzY1GjY2+Ous7BzWcDDlFAV2jlwDd3l1sEBZGL1IdHn/RSN2N3rn9nAcftKxN1jTYyv7ALlgB87TilNA94eP54la78B19h+Ba2K1M08yUoCY0jCnf2TUpCCj3sYoET4lUk+dC/GB8JxF+JSUycYCTIp/wJwyo3DnfPbrpc5loP3KP2y08ECcv1T7TsqvSupUhxZbPOxiQKBgQD28st6htWWXucgV/C5HZPOg4fAx2IQGKkqqNTD7YzfVWKcd1NSzPzL23ZO6gSfJfvYp53aTnnww83G1RPvK03Lt6cTUVfgQ5za3V/Z++xlxlQaosmyj9gf5VLh6s7gsgGPgok4xYJv4TWmDL1yhTVSXc4ROD0KGWqzzNKf8WrP4wKBgQDmRijwgQErmsUqHiLOL+0PKwXN5YxjkhqPu8cRj4cGdYxyS3YQmHZNbhUxGt3I7S5rM5tGU9FHMyyEnlq2xuLGgidORGibfQfWQYuK9i7S53yKgYTonHy/Zq45Wm+MtgG0iS+ITSo6EekcDOSUdEj3rhb0HkI2C5mQIpeDvesd5QKBgQDfB1bYWTBLt3h8kI/bUCguykHvzOL28J7P5V0Let7Q0XfXIjnBvVrO7m1CRj5YUeDLwk5hXKDq3pxZaBWx2uVPCJW/b6ay572hOXAZGlpdbKqGx+DsANfLrryVRxEChCG+r8Eo4dC1JKvkRPtQk5gdxJSYnrcaCOyCaIkNZOb3ywKBgG+xIDJnoFWyIGgpbeBsxqNQzuPrr4isWU3WWtxdrbSoV5Monv+1s8wi1QyYZ3MJ+DXvNiWKijvqynEZDg8RsPVwM/h2nfatUpvN9w1UE6ogtfvIjtr07F06RM902h56OaGD2RZXt1+rSFJevpBzRuE8A84szxi/z6Bl5u/zspMxAoGAIdES1uOXKozVN5GCFz/HnkuNSdShO6YnmCYFdn55ZT/NVXkIfvYu0+3bvdd6heg1wkYOZ4JzVqOkoOhmX2HaM/8kviooIS/+ZrLpojpTMTkUG2m87efNTznP7DKvPc5hKHBEHucx+6+AcaCvg23YlpDN5UsjVx+Dcx0fRd3I1p4=
  alipayPublicKey: MIIBIjANBgkqhFAAOCAQ8AMIIBCgKCAQEA1NZWZMTqEC9JaygVNPGmiBiLF3V5NLGS7MIOMHPG3uAbm+qPfaIFjHHvWEuXqiP6Y7h7FgG+HzJZp9AxuZVBD1Q82Bp1TTDFdTTXwebh6i3x5iA0L2i0b0fDbC4ug2WbQsjQp/QR7GH3XAaqMTDRlr6USNggf2uFCjQ0BqlkyM9pBKCJeuunF1cgwia8xc3vNf3f3H3+kfWSKmbPkRC2VVfoktlpM839+wszowgLoRIBqtW1xcfJztTFPKtTBdgFRYqW7thNn0MlzlXZYXgG1j/rYFyfLTRhB1DAIs+isHQwKuELeRu/ZHYvEIB8efWx9iNYeYQIDAQAB
  returnUrl: https://any-platform-test.shengsuvc.com/api/alipay/return
  notifyUrl: https://any-platform-test.shengsuvc.com/api/alipay/notify
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  signType: RSA2
  timeoutExpress: 2m
  productCode: QUICK_WAP_WAY
rocketmq:
  consumer:
    namesrvAddr: 127.0.0.1:9876
    group: anyGroup
