server:
  port: 9093
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/log-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: ss123456!@
  aop:
    proxy-target-class: true
zookeeper:
  #address: 192.168.1.52:2181
  address: 127.0.0.1:2181
dubbo:
  group: log-center
  port: 20883
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/log-center-service.log
rocketmq:
  consumer:
    logGroup: logGroup
    namesrvAddr: 127.0.0.1:9876
dingtalk:
  groupUrl: https://oapi.dingtalk.com/robot/send?access_token=92e306a3d642162d1f09082821d508d6b8f48cb5612ecb110da7ad9a2a7a4280
  msgUrl: http://192.168.1.52:9005/system/error_log
  picUrl: https://shengsu-public.oss-cn-hangzhou.aliyuncs.com/help-center/exception-local.png
