server:
  port: 9099
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/help-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: ss123456!@
  aop:
    proxy-target-class: true
  redis:
      host: 127.0.0.1
      #host: 192.168.1.52
      port: 6379
      timeout: 2000
      password: 123456
      database: 0
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 5000
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
zookeeper:
  address: 192.168.1.52:2181
  #address: localhost:2181
dubbo:
  group: help-center
  port: 20885
  version: 2.0
oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAISsw5CZys2sER
  accessKeySecret: 08pkECtJSNKPMwXnsYm3WSqdbkXm8h
  bucketName: shengsu-test
  timeout: 5000
  expiretime: 60000
sts:
  roleArn: acs:ram::1476735593452953:role/sts-oss
  roleSessionName: help-platform
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/help-center-service.log

###consumer
rocketmq:
  producer:
    namesrvAddr: 192.168.1.52:9876
    logGroup: logGroup
    jpushGroup: jpushGroup
    maxMessageSize: 131072
    sendMsgTimeout: 10000
  consumer:
      jpushGroup: jpushGroup
      namesrvAddr: 192.168.1.52:9876
      consumeThreadMin: 20
      consumeThreadMax: 64
      consumeMessageBatchMaxSize: 10
      consumeTimeout: 30

jiguang:
  apnsProduction: false
  appKey: c5320bf3f48ab3e2e4f6d809
  masterSecret: 340e3eac3a3ae754219cded9
sms:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accessKeyId: LTAI4Fdwm4oZHtE6SJdTJnDx
  accessKeySecret: It3EmApg1qSRoKoJuMItWtzoZAPIcY
  signName: 浙江援手律师事务所
pns:
  accessKeyId: b719d4aa71dd463db053af0e522c9e34
  accessKeySecret: 423ee45dac0e4991b396f3b867e0abcc





