server:
  port: 9099
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/help-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  aop:
    proxy-target-class: true
zookeeper:
  address: 192.168.1.52:2181
dubbo:
  group: help-center
  port: 20884
  version: 1.0
oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAISsw5CZys2sER
  accessKeySecret: 08pkECtJSNKPMwXnsYm3WSqdbkXm8h
  bucketName: shengsu-test
  timeout: 5000
  expiretime: 60000
sts:
  roleArn: acs:ram::1476735593452953:role/sts-oss
  roleSessionName: help-platform
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/help-center-service.log
