server:
  port: 9099
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/help-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: ss123456!@
  aop:
    proxy-target-class: true
  redis:
    host: 127.0.0.1
    #host: 192.168.1.52
    port: 6379
    timeout: 2000
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0
  data:
    elasticsearch:
      cluster-name: es
      cluster-nodes: 127.0.0.1:9300
zookeeper:
  #address: 192.168.1.52:2181
  address: 127.0.0.1:2181
dubbo:
  group: help-center
  port: 20885
  version: 2.0
oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAISsw5CZys2sER
  accessKeySecret: 08pkECtJSNKPMwXnsYm3WSqdbkXm8h
  bucketName: shengsu-test
  timeout: 5000
  expiretime: 60000
sts:
  roleArn: acs:ram::1476735593452953:role/sts-oss
  roleSessionName: help-platform
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/help-center-service.log

###consumer
rocketmq:
  producer:
    namesrvAddr: 127.0.0.1:9876
    group: helpGroup
  consumer:
    namesrvAddr: 127.0.0.1:9876
    group: jpushGroup

jiguang:
  apnsProduction: false
  appKey: c5320bf3f48ab3e2e4f6d809
  masterSecret: 340e3eac3a3ae754219cded9
sms:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accessKeyId: LTAI4Fdwm4oZHtE6SJdTJnDx
  accessKeySecret: It3EmApg1qSRoKoJuMItWtzoZAPIcY
pns:
  accessKeyId: b719d4aa71dd463db053af0e522c9e34
  accessKeySecret: 423ee45dac0e4991b396f3b867e0abcc