server:
  port: 9099
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl2ql.rds.aliyuncs.com:3306/help-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: d
    password: ss1234
  redis:
    host: 127.0.0.1
    #host: 192.168.1.52
    port: 6379
    timeout: 2000
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0
zookeeper:
  #address: 192.168.1.52:2181
  address: 127.0.0.1:2181
dubbo:
  group: help-center
  port: 20885
  version: 2.0
oss:
  endpoint: https://oss-cn-haou.al
  accessKeyId: LTAISswy
  accessKeySecret: 08pkECt
  bucketName: shengs
sts:
  roleArn: acs:ram::147673559
  roleSessionName: help-pl
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/help-center-service.log

###consumer
rocketmq:
  producer:
    namesrvAddr: 127.0.0.1:9876
    group: helpGroup
  consumer:
    namesrvAddr: 127.0.0.1:9876
    group: helpGroup
sms:
  product: Dysm
  domain: dysmsapi.a
  accessKeyId: LTAI4Fdwm4oZHtE6
  accessKeySecret: It3EmApg
pns:
  accessKeyId: b71
  accessKeySecret: 42
