server:
  port: 9088
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/website-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
zookeeper:
  address: 127.0.0.1:2181
dubbo:
  group: website-center
  port: 20887
  version: 1.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/website-center.log
lawknowledge:
  picture-range: 100
wechat:
  accessLoginUrl: https://api.weixin.qq.com/sns/jscode2session
  appID: wx36c1d8e71b07103d
  appSecret: 209cf3e6b10e170d73c2fcf24b7f4f55

