server:
  port: 9088
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/website-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
zookeeper:
  address: 127.0.0.1:2181
dubbo:
  group: website-center
  port: 20887
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/website-center.log
lawknowledge:
  picture-range: 100
wechat:
  shengsu:
    accessLoginUrl: https://api.weixin.qq.com/sns/jscode2session
    appID: wx36c1d8e71b07103d
    appSecret: 209cf3e6b10e170d73c2fcf24b7f4f55
  yuanshou:
    accessLoginUrl: https://api.weixin.qq.com/sns/jscode2session
    appID: wx22c0714da6b3d10b
    appSecret: 93df5324e1387778ad2fea1ebd2c4680
alipay:
  shengsu:
    appID: 2021001166640488
    decryptKey: sbSDBy48jZFsKtFQVQKZ7g==
    accessLoginUrl: https://openapi.alipay.com/gateway.do
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqNbp5+d3EQkTP4X2S/MQyQh/LGoy60TWMt4f3ItnREIzFYn/EsU6kR+oGo08+qlih8SLiUMGvp0DwoTfzRpY9ff0nwO9Rc3hZpVGlDbx3PCJr8LQQT9fsf1vFGm7YUWu9deCxvemE8WM+ZWMawkOlgO2Ynw6F6IkoTOXLEmLjy9gC9l9FvfIq1qd5QOX85CJwXmQFX0WiAAPb1K6vOM4o3pSSjo/w04E88nTVoYJw3YgeB2n8lF2oL0/GD704hls6IqU5R2iyyVQex9Epf3FSaORzA9zEXugvMBtowv+aEmsjiiGZZPD+IYAbZjcW1hKvKirqvsxosHzWvFjBaPbQQIDAQAB
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfosswfBmDg9XxjGnZ99j1JPzyk0dYFP7f5oVZ47AzUjlZaUDpSmlV9MH4EVk4kTKGaLCZziEDG6TTs6k6BYsQMJtlmV5oRuIJweqjId1ZZ8FWXrpS5JaBJwR8oYqNrc20CfaFAT0VKEnauQBYQG0AwtOCb0dlAgnbLstLQdSK7C6rU8yjxM8Nc5LcUaGezx/8kaSJci6aOl6kr6wQEZtscRBAQS/pdYGBONQlOoUlpLric92cbkPicbdJoiHcF1NJilAxqCgL7QeF1yr14nHljtE8uYv1udnhsnOHp65KOTRS5e16N66Wkj34ucUi4MMZhPZtvqknoUtOJJdL66MfAgMBAAECggEAO3BQG8N5dICYHpJbr28bd1vIW0H/ZIqcxB1/NZMTvmg1Nld8deDhC8JQnt9Gy0s09trwNrSLki6u1qykrBf4SZTvp4rNniIWc++iQA+R7YI2eMRYuBio+Xnfr9AuWMaIOysigS+O4NvZc/lCaZnDfG8OdhidCr0Rkm0AAQuH6hmkSuNGDIQ7BqLn9Ja547RI3Hq7s/l8M+2gzSzc4wQ9HHaKdaAbnnE7QqQfksoi12BYmq06+zKrnVCT046jjTlgYhuzhikpPXIo8WgXAHj7qykq8BaSVg3ZpT3fh3sUCFXLnaE4ykslVemfOL4La2dly9glsmQKuPqc4AisejbgEQKBgQDOkI4ax7aVWH/hwAmGhHGc16owt5ST9NW9xipOhhl9yBte4q9OmYfGJJ5wAZX7GgwOjHX/n2Sezcl/FSos9Hh2O4v8YdN1IOU2RXQp1X6I38Rga0KltcmU4M6QLV9X+0bpFg4Os3v67at/U5vHz9elt4dFnkUo1nnZhAKk3eA0RQKBgQDF1xbXxqwOVAQtaZe/gzW+5H51B4D8+SzvT+O9w10kaWZ3+nIJnNbdX+y4yqP/YZFUaTvZ6dfIikzvtgw+uHGL9w8zYBL6u5Nn4pDd1D9GPl7Ct+SGe1t4GpkZvpcxMpSsWQ4anyl7oIT/yjiHqem7+MnUCIxPcIILuhYQ3YHaEwKBgHXNLK2LHc5YFT4qZYRIff6DY7S6zUn/w/GhVLlJcrov56QaRP3fQvY2JgEcdmsodJ3LbvPj89843uPRrybKGPTcir3ZEF3o768ettuwvKPUcUrHgM++N4LnHgZNSeWEEPGWuVea9mapKjfH97xhBMumOcfzNd/PSNhKl7NsMZO9AoGBAJBal81LpkEyJnYoRNQ1XeLygB7OIdzzx0i6hxbwVKb7zQugDtNawCB5HJXdLfpqa4sm2cfv60XlO6vwrlCZbihNVacL4+1VLoIve7qQYrbTTXtQiItjuOMSrUFuoo0ANiDnPfZIyhDtl/23xLWgUe6Y4lM3BYH1Or5pwi3+IgBHAoGAdTX+xU18oSXImjVDerLDplG1XNaIUNmJUWsMXpSLHLePHbHEV7HdQgW3kKbWRWdyxb9M+f5thq0pr9XG+zY6Cy9hsIxQSwYgYE/Gg+66g1trY0DXryPo+PePFvP9VIyQIdqVK56r2m4Qe7BW2aTABBo7HKgk9qv5co0T+2M4tbI=
  yuanshou:
    appID: 2021001166685393
    decryptKey: UkKAlXdXFZlCs+dK3+5dGQ==
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1TeItoHnjhKLxHP6xhDd4eRGcNk59RwbuvcdRoV1PbX/4EbnYOPaTXJWQdNLHBiHkpxpnRqpn8wsi1vNoSxvczW2ptg/G/1lI6iJvY7b/2UgzJ33NlKcgJRLE9tvVnDmAFMH0wdwLEL27nGX6KQ6jpl6F8Nd9eucKDctkNBGFx3d3A1YamL8LT9s++qM9Mq1Ue451t1HBVmN8y9+RTDI7NLQq68zQyeH6IC6aLyex8VXuUtZVwZ/es3sDZbd3YCYnQNGSlGi3edo/C1MVcnot7GXQNNBQQRcM+brgiNiovediilIQsdM3IlM2bGxys/kpSI97rPHB1NFImW6bXEdSQIDAQAB
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCUz1Tg0rR7N/1E8HBiKmxfa7rkSY5uprQQh/doWEvQyZL6ldga2cPX1Tsd0FrVsUysfrgLuhRSHIDgsFmdf0fL1ySavU5yddKj1c1nkdk4Qu3ELCJnqBY+nykq9aPuwRPntUCIApR8VoghhJPxRhoCeBxDo2s9G1m6pEfmu/FHGMw75DZb8vsKuXDn8QsVf6/gEKTKm5OP0XZA/k9I/GRaSKdK4fif46zkZ717JvxUJb1scigXZBThF50ytwQQNkcj9X9KDVa2ks5qDK+UqaEcqN1a11Tj0tCohQG+hv/yoP8xbVjY5HvZASMBhTtMhduvma0K9MpSPGZ9XT+KA6gLAgMBAAECggEBAIGWzGO9Gk7zwyt192iFaTrvpiGHrPHPWp/KyDmmKt/3qnduZnN7kIE0v/aGq5PMguj0sXIE6g1XpSQGbwQpA20QPmBC2z3yPS1P00COUowcPNLJXGzIhBakpEU1BT22Bo+R2FCZbpWZBZOq0OscESp1TqfYeFsOpmVTCwp0QPmX1FqoJSPTQMMSLVZKFwyNxByZTvKU/Tqcl1Czu19y6E3hZcT4u003ReGQEQz0Hx1p5kQsUpU/HdUJdjgRyxPNoqcDWKc7WD9Y6MlgxzzT5rawfFUIkP8LbTzuY2zrj3GG8yRdYXB6dt928+gJ0yPeBE/42IGbcCniAiXjWflxIoECgYEA7SLyTUfQOBgDKCC8cQEcjbvt8SdumH8Rsp5ggVFnhdGMlRdHPDgmCXnHHr8NiexFmj9tYhcGepkenNAWcSTqMTSp2S5I/9mVeXUBjqkyfg2sdSpE9YXZDlvQy9I24LZwpPhP0MLyGs4ZToHMKIZJObQ76AJH7nDg07mEiioEx58CgYEAoKWzHQ63KMKKt/trhGAnWMhaxfT5hfCyMPOYFKUyzE0fdGy9QXAyrf+qObKH6sFnHk3gklIaV1+yCxJs4tg9RbZItTRLRHFCVk+AUxjYXjhvp4l4uVTOI94zBlx+EgrtOjwy9uga0uU8kvp1RfS860ReO+iBSYT7NJGVY8m7uBUCgYAy/lnWjoPTHC7JmUiMkG2gePIw8obQ2jpnC7G6/VNirm4pvWi/JV/gl8Re8zypFRrekZcnCcaF5Jl1pTW+PO7zh9yibFacViDTjnq4P+AwxSX5yA4uMgs8EDh1LA5LAlB02UToopNHelxsynKpoD7s3ronKR5owvNF9FXxFBoVBwKBgBp1cBy3Eb+q2wIWbMzusUxUI287O+WtkQuy8zdjRgyUHzwjtMAUZKR32WeLWgt2My+wj+5Ji4Ech8x/CmQKTX0v2qXNqR/qr4xbp70H+Ir8LJehcrrDlvgdXrYLgdAi8JOI2rQD4ncdvm5OxgXxmzP8nLCtSK39Mwqjd8FptntJAoGAWi2Elp9oX2XvaJcZ9mIyv6NGf7/3LtR0LXWQAct/8zy1F6rT3G4CzBg7lJBzoLgT3ZrjMq4XY3YkvMqrsWIIUUtEaO0qtoQYp7Ssx7zzOwLW1e8aVPDuuAiRO0o706icRVGSEiZ4lo5XF1foue5mdd62XqHUpNaQAT8reA/+vKo=