server:
  port: 9088
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/website-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
zookeeper:
  address: 127.0.0.1:2181
dubbo:
  group: website-center
  port: 20887
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/website-center.log
lawknowledge:
  picture-range: 100
wechat:
  shengsu:
    accessLoginUrl: https://api.weixin.qq.com/sns/jscode2session
    appID: wx36c1d8e71b07103d
    appSecret: 209cf3e6b10e170d73c2fcf24b7f4f55
  yuanshou:
    accessLoginUrl: https://api.weixin.qq.com/sns/jscode2session
    appID: wx22c0714da6b3d10b
    appSecret: 93df5324e1387778ad2fea1ebd2c4680
alipay:
  appconfig:
    decryptKey: UkKAlXdXFZlCs+dK3+5dGQ==
    signVeriKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1TeItoHnjhKLxHP6xhDd4eRGcNk59RwbuvcdRoV1PbX/4EbnYOPaTXJWQdNLHBiHkpxpnRqpn8wsi1vNoSxvczW2ptg/G/1lI6iJvY7b/2UgzJ33NlKcgJRLE9tvVnDmAFMH0wdwLEL27nGX6KQ6jpl6F8Nd9eucKDctkNBGFx3d3A1YamL8LT9s++qM9Mq1Ue451t1HBVmN8y9+RTDI7NLQq68zQyeH6IC6aLyex8VXuUtZVwZ/es3sDZbd3YCYnQNGSlGi3edo/C1MVcnot7GXQNNBQQRcM+brgiNiovediilIQsdM3IlM2bGxys/kpSI97rPHB1NFImW6bXEdSQIDAQAB