server:
  port: 9088
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/website-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 2000
      password: 123456
      database: 0
      jedis:
        pool:
          max-active: 100
          max-wait: 5000
          max-idle: 10
          min-idle: 0
zookeeper:
  address: 192.168.1.52:2181
dubbo:
  group: website-center
  port: 20887
  version: 1.0
logging:
  file: logs/website-center.log




