server:
  port: 9092
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
zookeeper:
  address: 127.0.0.1:2181
dubbo:
  group: user-center
  port: 20882
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.shengsu.*.model
logging:
  file: logs/user-center-service.log
token:
  secretKey: 97c7d3b3313d31b8#3996a!*1dd85c9711fc1f4?e35<0c9052683e63a
  expireTimeSecond: 3600
