server:
  port: 9092
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
  redis:
    #host: 127.0.0.1
    host: 192.168.1.52
    port: 6379
    timeout: 2000
    password: 123456
    database: 4
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
zookeeper:
  address: 192.168.1.52:2181
  #address: 127.0.0.1:2181
dubbo:
  group: user-center
  port: 20882
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.shengsu.*.model
logging:
  file: logs/user-center-service.log
# Token
token:
  secretKey: 97c7d3b3313d31b8#3996a!*1dd85c9711fc1f4?e35<0c9052683e63a
  expireTimeSecond: 3600
