server:
  port: 9087
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/trade-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
  redis:
      host: 172.16.20.122
      port: 6379
      timeout: 2000
      password: 123456
      database: 0
      jedis:
        pool:
          max-active: 100
          max-wait: 5000
          max-idle: 10
          min-idle: 0
zookeeper:
  address: 172.16.20.122:2181
dubbo:
  group: trade-center
  port: 20888
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/trade-center.log
wxpay:
  appid: wx6f29705e50768a15
  mchid: 1573621631
  apikey: 1f5dc3037d7a4752b69e95fcad34ad34
  sandbox: false
  notifyUrl: https://any-platform-test.shengsuvc.com/api/wxpay/notify
alipay:
  appid: 2016101900724821
  rsaPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeIdCxqIAk+8cvqmMmoVGoPG3+Z4P+TmgzNDxktOOvNIWV1opwZffvTGEq3Z70RZtGJC5Q0ojQma/jGWPzEP2qsjZOteJTVMWiCjSrbWAUwh23tsiNLNYiG+aGKfDf74MOI63cYuGeIz7gU+jd+1jxuHGgEzHr1PpTP4/AOAtFyvR8BjTuBL5j3AYWohaANynWjHZUw+phA7dmK7/7atHlMTcLFOQzt+mhutbaccVMx+IWAjC+u3QGKHIDccLoaMMkml/gwTWV8W2jqB+kGh12lqE1R/SBrU/qYV1kSwy/goIfQ0q7Pj5z1qU9Jg1vcvJYDTxI3VhbX06QRhx6ea0PAgMBAAECggEABhq1ynwP8XQ92BB9ow0h2la2yxv7I5zx/h48XqQd8a2m0iRQL6CNvLTDotLuUFYtWzMZVr1CZ0Eh9UK4XXClF/DHz0fuTU3yFG7lXaSm1Es1V9wdDMwjolJT9nHmnbDOUDAo0fqhqp/bVXzY1GjY2+Ous7BzWcDDlFAV2jlwDd3l1sEBZGL1IdHn/RSN2N3rn9nAcftKxN1jTYyv7ALlgB87TilNA94eP54la78B19h+Ba2K1M08yUoCY0jCnf2TUpCCj3sYoET4lUk+dC/GB8JxF+JSUycYCTIp/wJwyo3DnfPbrpc5loP3KP2y08ECcv1T7TsqvSupUhxZbPOxiQKBgQD28st6htWWXucgV/C5HZPOg4fAx2IQGKkqqNTD7YzfVWKcd1NSzPzL23ZO6gSfJfvYp53aTnnww83G1RPvK03Lt6cTUVfgQ5za3V/Z++xlxlQaosmyj9gf5VLh6s7gsgGPgok4xYJv4TWmDL1yhTVSXc4ROD0KGWqzzNKf8WrP4wKBgQDmRijwgQErmsUqHiLOL+0PKwXN5YxjkhqPu8cRj4cGdYxyS3YQmHZNbhUxGt3I7S5rM5tGU9FHMyyEnlq2xuLGgidORGibfQfWQYuK9i7S53yKgYTonHy/Zq45Wm+MtgG0iS+ITSo6EekcDOSUdEj3rhb0HkI2C5mQIpeDvesd5QKBgQDfB1bYWTBLt3h8kI/bUCguykHvzOL28J7P5V0Let7Q0XfXIjnBvVrO7m1CRj5YUeDLwk5hXKDq3pxZaBWx2uVPCJW/b6ay572hOXAZGlpdbKqGx+DsANfLrryVRxEChCG+r8Eo4dC1JKvkRPtQk5gdxJSYnrcaCOyCaIkNZOb3ywKBgG+xIDJnoFWyIGgpbeBsxqNQzuPrr4isWU3WWtxdrbSoV5Monv+1s8wi1QyYZ3MJ+DXvNiWKijvqynEZDg8RsPVwM/h2nfatUpvN9w1UE6ogtfvIjtr07F06RM902h56OaGD2RZXt1+rSFJevpBzRuE8A84szxi/z6Bl5u/zspMxAoGAIdES1uOXKozVN5GCFz/HnkuNSdShO6YnmCYFdn55ZT/NVXkIfvYu0+3bvdd6heg1wkYOZ4JzVqOkoOhmX2HaM/8kviooIS/+ZrLpojpTMTkUG2m87efNTznP7DKvPc5hKHBEHucx+6+AcaCvg23YlpDN5UsjVx+Dcx0fRd3I1p4=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1NKEKwl4sUMEP7vZiZWZMTqEC9JaygVNPGmiBiLF3V5NLGS7MIOMHPG3uAbm+qPfaIFjHHvWEuXqiP6Y7h7FgG+HzJZp9AxuZVBD1Q82Bp1TTDFdTTXwebh6i3x5iA0L2i0b0fDbC4ug2WbQsjQp/QR7GH3XAaqMTDRlr6USNggf2uFCjQ0BqlkyM9pBKCJeuunF1cgwia8xc3vNf3f3H3+kfWSKmbPkRC2VVfoktlpM839+wszowgLoRIBqtW1xcfJztTFPKtTBdgFRYqW7thNn0MlzlXZYXgG1j/rYFyfLTRhB1DAIs+isHQwKuELeRu/ZHYvEIB8efWx9iNYeYQIDAQAB
  returnUrl: https://any-platform-test.shengsuvc.com/api/alipay/return
  notifyUrl: https://any-platform-test.shengsuvc.com/api/alipay/notify
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  signType: RSA2
  timeoutExpress: 2m
  productCode: QUICK_WAP_WAY




