server:
  port: 9087
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o00hl21xvv5eq7no.mysql.rds.aliyuncs.com:3306/trade-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: 'ss123456!@'
  aop:
    proxy-target-class: true
zookeeper:
  #address: 47.98.159.202:2181
  address: 127.0.0.1:2181
dubbo:
  group: trade-center
  port: 20888
  version: 2.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  file: logs/trade-center.log
wxpay:
  gzh:
    appid: wx6f29705e50768a15
  weapp:
    appid: wx36c1d8e71b07103d
  mchid: 1573621631
  apikey: 1f5dc3037d7a4752b69e95fcad34ad34
  sandbox: false
  notifyUrl: https://platform-test.yuanshoulawyer.com/api/wxpay/notify
alipay:
  appid: 2016101900724821
  rsaPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeIdCxqIAk+8cvqmMmoVGoPG3+Z4P+TmgzNDxktOOvNIWV1opwZffvTGEq3Z70RZtGJC5Q0ojQma/jGWPzEP2qsjZOteJTVMWiCjSrbWAUwh23tsiNLNYiG+aGKfDf74MOI63cYuGeIz7gU+jd+1jxuHGgEzHr1PpTP4/AOAtFyvR8BjTuBL5j3AYWohaANynWjHZUw+phA7dmK7/7atHlMTcLFOQzt+mhutbaccVMx+IWAjC+u3QGKHIDccLoaMMkml/gwTWV8W2jqB+kGh12lqE1R/SBrU/qYV1kSwy/goIfQ0q7Pj5z1qU9Jg1vcvJYDTxI3VhbX06QRhx6ea0PAgMBAAECggEABhq1ynwP8XQ92BB9ow0h2la2yxv7I5zx/h48XqQd8a2m0iRQL6CNvLTDotLuUFYtWzMZVr1CZ0Eh9UK4XXClF/DHz0fuTU3yFG7lXaSm1Es1V9wdDMwjolJT9nHmnbDOUDAo0fqhqp/bVXzY1GjY2+Ous7BzWcDDlFAV2jlwDd3l1sEBZGL1IdHn/RSN2N3rn9nAcftKxN1jTYyv7ALlgB87TilNA94eP54la78B19h+Ba2K1M08yUoCY0jCnf2TUpCCj3sYoET4lUk+dC/GB8JxF+JSUycYCTIp/wJwyo3DnfPbrpc5loP3KP2y08ECcv1T7TsqvSupUhxZbPOxiQKBgQD28st6htWWXucgV/C5HZPOg4fAx2IQGKkqqNTD7YzfVWKcd1NSzPzL23ZO6gSfJfvYp53aTnnww83G1RPvK03Lt6cTUVfgQ5za3V/Z++xlxlQaosmyj9gf5VLh6s7gsgGPgok4xYJv4TWmDL1yhTVSXc4ROD0KGWqzzNKf8WrP4wKBgQDmRijwgQErmsUqHiLOL+0PKwXN5YxjkhqPu8cRj4cGdYxyS3YQmHZNbhUxGt3I7S5rM5tGU9FHMyyEnlq2xuLGgidORGibfQfWQYuK9i7S53yKgYTonHy/Zq45Wm+MtgG0iS+ITSo6EekcDOSUdEj3rhb0HkI2C5mQIpeDvesd5QKBgQDfB1bYWTBLt3h8kI/bUCguykHvzOL28J7P5V0Let7Q0XfXIjnBvVrO7m1CRj5YUeDLwk5hXKDq3pxZaBWx2uVPCJW/b6ay572hOXAZGlpdbKqGx+DsANfLrryVRxEChCG+r8Eo4dC1JKvkRPtQk5gdxJSYnrcaCOyCaIkNZOb3ywKBgG+xIDJnoFWyIGgpbeBsxqNQzuPrr4isWU3WWtxdrbSoV5Monv+1s8wi1QyYZ3MJ+DXvNiWKijvqynEZDg8RsPVwM/h2nfatUpvN9w1UE6ogtfvIjtr07F06RM902h56OaGD2RZXt1+rSFJevpBzRuE8A84szxi/z6Bl5u/zspMxAoGAIdES1uOXKozVN5GCFz/HnkuNSdShO6YnmCYFdn55ZT/NVXkIfvYu0+3bvdd6heg1wkYOZ4JzVqOkoOhmX2HaM/8kviooIS/+ZrLpojpTMTkUG2m87efNTznP7DKvPc5hKHBEHucx+6+AcaCvg23YlpDN5UsjVx+Dcx0fRd3I1p4=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1NKEKwl4sUMEP7vZiZWZMTqEC9JaygVNPGmiBiLF3V5NLGS7MIOMHPG3uAbm+qPfaIFjHHvWEuXqiP6Y7h7FgG+HzJZp9AxuZVBD1Q82Bp1TTDFdTTXwebh6i3x5iA0L2i0b0fDbC4ug2WbQsjQp/QR7GH3XAaqMTDRlr6USNggf2uFCjQ0BqlkyM9pBKCJeuunF1cgwia8xc3vNf3f3H3+kfWSKmbPkRC2VVfoktlpM839+wszowgLoRIBqtW1xcfJztTFPKtTBdgFRYqW7thNn0MlzlXZYXgG1j/rYFyfLTRhB1DAIs+isHQwKuELeRu/ZHYvEIB8efWx9iNYeYQIDAQAB
  returnUrl:
    any: https://any-h5-test.shengsuvc.com/finance/complete
    market: https://market-h5-test.shengsuvc.com/pages/service/service
  notifyUrl: https://platform-test.yuanshoulawyer.com/api/alipay/notify
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
bdpay:
  appKey: MMUv5L
  appId: 31280
  dealId: 671485529
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKh8FlYteSUg2ejB0MZ8prTno5xMU8ZO+XI9D4YAyTI6/mZYqD/VSKzLYS6OX/VTdlDRWp47TcX8/UEASwXklMKK+7w0qcXUyMQxEb8MNhEfDYYyXSoOODsjDw+tp/YEVLL5mqYvZMIHin4vJQkmtHeMC0KymkxiP9lEqFZkQ/0rAgMBAAECgYAqGEakZVwdMKYBB1uYG9Cy5iT0igVsSJL+Pc9BFbUu/ZpOC9yNhkZQFchED4JeEuo+qu/PFNYLn3fO47na0Q9xW85bap6bJ7Fg+M4Sv70jRa2U7u7qip29iwxhoi7ZC9LDAn64W5b9O9quqFnhRsnw63fCrtv6fWjkPByeL7yx8QJBANnl/Z2YFw2Hb08x6RKAaTo/VDgBsjMEcaDvJOcAT3apHLR8Xyf/WWYlkvtg9WeuY0i0/1RbFt8vjd/EPoM5iz0CQQDF8iQjB3YVM2AK4hAbi2U/IOR0LxsGkW+A6AdQ21G1up1JL/5izk250RINs/q4cC4BuUo811fi4b2KtpeTktCHAkEAiXwDTNd03DVzNw3v2JurSXRB6GCxll0ccQXTS+m3OdC0avD6fVsxhjD5D6F61iODQ5HodMpQoRv5MZI6O0QopQJBAL1z3Nxd9smhy0l/RlVmnDfIfn8o2p/1sJfa+62Ky/C4NHPo6Hue4st26+WLnerLC22A7ym+HZK75hKOYhLPUJ8CQFp95h4W1kUK2wpZ6roNFTOSKA4jqQn3xHSJ51xrF9CURWAG31wMmEDReG74z/1nnUGzwg1b6XV0eZZHRM7uen0=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIPak4h0pP5/KobxxQRNo4VE7ulen1OV+HfPmARS0Fmqgh8eKQrHOocX3m0crfIUmFr+e3O5RDk+Q8G+98AR6nWaVGRIGnwcwpzaC35jWTYOlqgsG37xQfv90Kkfa8DkUJX9DJapl9ri78GTpDZs6kFFERMZP9/pWJcN7QdKXZtwIDAQAB
rocketmq:
  consumer:
    namesrvAddr: 127.0.0.1:9876
    group: websiteGroup


