server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  aop:
    proxy-target-class: true
zookeeper:
  address: 192.168.1.52:2181
  #address: 127.0.0.1:2181
dubbo:
  group: lawcase-center
  port: 20881
  version: 1.0
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.shengsu.*.model
logging:
  file: logs/user-center-service.log
